server:
  port: 9090
  servlet:
    context-path: /
spring:
  mail:
    host: smtp.gmail.com 
    port: 587
    protocol: smtp
    username: qppk123@gmail.com
    password: huvozcvaoscprwqj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    maria:
      jdbc-url: jdbc:mariadb://127.0.0.1:3306/mercury?useUnicode=yes&characterEncoding=UTF-8
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: skrbxo12!@
  jpa:
    hibernate:
      ddl-auto: true
    properties:
      hibernate:  
        show_sql: false
        format_sql: true
    generate-ddl: true
#  quartz:
#    job-store-type: jdbc
#logging:
#  level:
#    root: DEBUG